/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Terminal Ghost Ops custom tokens
        "bg-primary": "#0A0E14",
        "bg-secondary": "#0F1419",
        "bg-tertiary": "#131B23",
        "bg-terminal": "#0C1117",
        "bg-input": "#1A2332",
        "bg-hover": "#1E2A3A",
        "border-subtle": "#1E2D3D",
        "border-active": "#2A4365",
        "neon-green": "#00FF88",
        "neon-cyan": "#00E5FF",
        "neon-blue": "#4488FF",
        "text-primary": "#E8EDF2",
        "text-secondary": "#8B9EB0",
        "text-muted": "#4A6072",
        "text-terminal": "#E6DCCF",
        "text-terminal-dim": "#5C7A8C",
        "text-green": "#00FF88",
        "text-cyan": "#00E5FF",
        "text-yellow": "#FFD166",
        "text-red": "#FF4757",
        "status-success": "#00FF88",
        "status-warning": "#FFD166",
        "status-danger": "#FF4757",
        "status-info": "#00E5FF",
        "status-purple": "#C77DFF",
        "status-orange": "#FF6B35",
        // Risk level colors
        "risk-green": "#00FF88",
        "risk-blue": "#00E5FF",
        "risk-yellow": "#FFD166",
        "risk-red": "#FF4757",
        "risk-purple": "#C77DFF",
        "risk-black": "#FF6B35",
        // Skill domain colors
        "skill-filesystem": "#00FF88",
        "skill-git": "#FF6B35",
        "skill-vim": "#C77DFF",
        "skill-network": "#00E5FF",
        "skill-process": "#FFD166",
        "skill-security": "#FF4757",
        "skill-docker": "#2496ED",
        "skill-shell": "#E8EDF2",
        // Achievement tier colors
        "tier-bronze": "#CD7F32",
        "tier-silver": "#C0C0C0",
        "tier-gold": "#FFD700",
        "tier-platinum": "#00E5FF",
      },
      fontFamily: {
        jetbrains: ['"JetBrains Mono"', 'monospace'],
        fira: ['"Fira Code"', 'monospace'],
        inter: ['"Inter"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'h1': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'h2': ['2rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h3': ['1.5rem', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h4': ['1.125rem', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body': ['0.875rem', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['0.75rem', { lineHeight: '1.5', letterSpacing: '0.01em', fontWeight: '400' }],
        'code': ['0.8125rem', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'code-sm': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'nav': ['0.8125rem', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'badge': ['0.625rem', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '600' }],
        'hud': ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.03em', fontWeight: '400' }],
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
        'space-16': '64px',
        'space-20': '80px',
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        'radius-sm': '4px',
        'radius-md': '6px',
        'radius-lg': '8px',
        'radius-full': '9999px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'green-glow': '0 0 20px rgba(0,255,136,0.08)',
        'cyan-glow': '0 0 16px rgba(0,229,255,0.08)',
        'red-glow': '0 0 24px rgba(255,71,87,0.12)',
        'panel-depth': '0 4px 24px rgba(0,0,0,0.4)',
        'panel-hover': '0 8px 32px rgba(0,0,0,0.5)',
        'terminal-inset': 'inset 0 0 40px rgba(0,0,0,0.3)',
      },
      transitionDuration: {
        'instant': '80ms',
        'fast': '150ms',
        'normal': '300ms',
        'slow': '500ms',
        'cinematic': '800ms',
      },
      transitionTimingFunction: {
        'default-ease': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'bounce-ease': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'terminal-ease': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 12px rgba(0,229,255,0.4)" },
          "50%": { boxShadow: "0 0 20px rgba(0,229,255,0.6)" },
        },
        "pulse-zap": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.1)" },
        },
        "skeleton-pulse": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "pulse-zap": "pulse-zap 2s ease-in-out infinite",
        "skeleton-pulse": "skeleton-pulse 1.5s ease-in-out infinite",
      },
      zIndex: {
        'bg': '-1',
        'content': '0',
        'elevated': '10',
        'floating': '20',
        'overlay': '30',
        'toast': '40',
        'critical': '50',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
